In [6]:
# importing pandas library
import pandas as pd

# Loading the DESeq2 result file 
df = pd.read_csv('results/result.txt', sep='\t')

# Sorting by "ranking"
df = df.sort_values('ranking')

# Showing the dataframe
display(df)

,rownames(data),SRR11309003,SRR11309004,SRR11309005,SRR11309006,p.value,q.value,ranking,log2.FC
34457,gene-SDC4|SDC4,1235,1140,36801,30092,0.0,0.0,56.0,4.642709
6644,gene-TRANK1|TRANK1,30,28,20474,17251,0.0,0.0,56.0,9.181360
41192,gene-HLA-A-4|HLA-A,11318,9127,169439,135175,0.0,0.0,56.0,3.731645
33083,gene-POU2F2|POU2F2,95,92,11265,9454,0.0,0.0,56.0,6.623634
33046,gene-AXL|AXL,63,65,61300,44725,0.0,0.0,56.0,9.516527
...,...,...,...,...,...,...,...,...,...
58081,gene-KIR2DL2-9|KIR2DL2,0,0,0,0,1.0,1.0,48237.5,NaN
58082,gene-KIR2DS2-13|KIR2DS2,0,0,0,0,1.0,1.0,48237.5,NaN
58083,gene-KIR3DL3-47|KIR3DL3,0,0,0,0,1.0,1.0,48237.5,NaN
58084,gene-LILRP2-42|LILRP2,0,0,0,0,1.0,1.0,48237.5,NaN
0,gene-FAM138A|FAM138A,0,0,0,0,1.0,1.0,48237.5,NaN